INSERT INTO products (name, description, price, image_url, stock_quantity, category_id, rating)
VALUES
    ('Wireless Headphones',
     'Over-ear wireless headphones with cushioned cups and a built-in microphone. A full charge covers a long commute and a quiet evening of music.',
     2499.00, '/images/wireless-headphones.jpg', 35,
     (SELECT id FROM categories WHERE name = 'Electronics'), 4.6),
    ('Smart Watch',
     'A lightweight smart watch for steps, heart rate, and phone notifications. The strap is comfortable enough for all-day wear.',
     3999.00, '/images/smart-watch.jpg', 22,
     (SELECT id FROM categories WHERE name = 'Electronics'), 4.4),
    ('Bluetooth Speaker',
     'A compact speaker with room-filling sound for a desk or a small gathering. Pair it once and carry it from study table to balcony.',
     1799.00, '/images/bluetooth-speaker.jpg', 30,
     (SELECT id FROM categories WHERE name = 'Electronics'), 4.5),
    ('USB-C Laptop Stand',
     'An aluminium stand that lifts a laptop to eye level and keeps the desk cooler. It folds flat so it fits in a college bag.',
     1299.00, '/images/laptop-stand.jpg', 18,
     (SELECT id FROM categories WHERE name = 'Electronics'), 4.3),
    ('Mechanical Keyboard',
     'A tactile mechanical keyboard for long notes, code, and assignments. The layout stays comfortable through a full evening of typing.',
     3499.00, '/images/mechanical-keyboard.jpg', 15,
     (SELECT id FROM categories WHERE name = 'Electronics'), 4.7),
    ('Cotton T-Shirt',
     'A soft cotton t-shirt with a regular fit and a neckline that keeps its shape after washing. Easy to wear with jeans or shorts.',
     599.00, '/images/cotton-tshirt.jpg', 80,
     (SELECT id FROM categories WHERE name = 'Fashion'), 4.2),
    ('Running Shoes',
     'Light running shoes with a cushioned sole for daily jogs and walking. The mesh upper stays breathable in warm weather.',
     2199.00, '/images/running-shoes.jpg', 25,
     (SELECT id FROM categories WHERE name = 'Fashion'), 4.6),
    ('Denim Jacket',
     'A mid-wash denim jacket to throw over a tee or shirt. Straight cut, with pockets that actually hold a phone.',
     2499.00, '/images/denim-jacket.jpg', 16,
     (SELECT id FROM categories WHERE name = 'Fashion'), 4.4),
    ('Casual Backpack',
     'An everyday backpack with a padded laptop sleeve and a front pocket for keys and a water bottle.',
     1499.00, '/images/casual-backpack.jpg', 28,
     (SELECT id FROM categories WHERE name = 'Fashion'), 4.5),
    ('Sports Cap',
     'A curved-brim sports cap in breathable cotton for sunny walks and practice. This style is currently out of stock.',
     399.00, '/images/sports-cap.jpg', 0,
     (SELECT id FROM categories WHERE name = 'Fashion'), 4.1),
    ('Basmati Rice',
     'Aged basmati rice with long grains that stay separate after cooking. A 1 kg pack for biryani, pulao, and everyday meals.',
     189.00, '/images/basmati-rice.jpg', 100,
     (SELECT id FROM categories WHERE name = 'Grocery'), 4.8),
    ('Organic Green Tea',
     'Green tea bags with a light grassy taste and no added sugar. Twenty-five bags in a resealable pack.',
     249.00, '/images/green-tea.jpg', 60,
     (SELECT id FROM categories WHERE name = 'Grocery'), 4.3),
    ('Coffee Beans',
     'Medium-roast arabica beans with cocoa and nut notes. Sold whole, so you can grind them just before brewing.',
     499.00, '/images/coffee-beans.jpg', 40,
     (SELECT id FROM categories WHERE name = 'Grocery'), 4.7),
    ('Oats',
     'Rolled oats for porridge, overnight jars, and baking. A 1 kg pack sized for weekday breakfasts.',
     179.00, '/images/oats.jpg', 70,
     (SELECT id FROM categories WHERE name = 'Grocery'), 4.4),
    ('Mixed Nuts',
     'A roasted mix of almonds, cashews, and raisins with no extra sugar coating. Handy for a desk drawer or tiffin.',
     399.00, '/images/mixed-nuts.jpg', 45,
     (SELECT id FROM categories WHERE name = 'Grocery'), 4.6),
    ('Stainless Steel Bottle',
     'A double-walled steel bottle that keeps water cold through class or a commute. 750 ml with a leak-resistant cap.',
     699.00, '/images/steel-bottle.jpg', 50,
     (SELECT id FROM categories WHERE name = 'Home & Kitchen'), 4.5),
    ('Non-Stick Frying Pan',
     'A 24 cm frying pan with a non-stick surface for eggs, dosas, and everyday sabzi. Suitable for gas stoves.',
     899.00, '/images/frying-pan.jpg', 20,
     (SELECT id FROM categories WHERE name = 'Home & Kitchen'), 4.3),
    ('LED Desk Lamp',
     'An LED desk lamp with a flexible neck for reading and late study sessions. The light stays even across a notebook.',
     799.00, '/images/desk-lamp.jpg', 24,
     (SELECT id FROM categories WHERE name = 'Home & Kitchen'), 4.4),
    ('Kitchen Storage Set',
     'A set of clear airtight containers for rice, dal, snacks, and spices. They stack neatly inside a cupboard.',
     1199.00, '/images/storage-set.jpg', 14,
     (SELECT id FROM categories WHERE name = 'Home & Kitchen'), 4.2),
    ('Electric Kettle',
     'A 1.5 litre electric kettle with auto shut-off for tea, coffee, and instant noodles. It boils quickly and switches itself off.',
     999.00, '/images/electric-kettle.jpg', 19,
     (SELECT id FROM categories WHERE name = 'Home & Kitchen'), 4.6);
